# redis type DB
db:
  pass: "password"
  host: "hostname"
  port: 1234
  id: 0

# thetvdb api info
the_tvdb_api:
  username: "YOURUSERNAME"
  user_key: "YOURUSERKEY"
  api_key: "YOURAPIKEY"

# transmission RPC URL
rpc_url: "http://transmission-host:9091/transmission/rpc"
username: "transmission_user"
password: "transmission_pass"

# RSS feed list
feeds:
  - "https://feed1/rss"
  - "https://feed2/rss"

# titles to look for
titles:
  - "Title 1"
  - "Title 2"
  - "Title 3"
